#!/bin/sh
set -eu
cd "$(dirname "$0")"

if [ -e void-packages ]; then
	void-packages/xbps-src clean
	git -C void-packages reset --hard >/dev/null
else
	git clone https://github.com/void-linux/void-packages.git
	ln -s void-packages/hostdir/binpkgs binpkgs
fi

cd void-packages/srcpkgs
ls ../../srcpkgs | xargs rm -rf
cd ../..
cp -r srcpkgs/* void-packages/srcpkgs

for package in "$@"; do
	void-packages/xbps-src pkg "$package"
done
