#!/bin/sh
set -eu
cd "$(dirname "$0")"

if [ -e void-packages ]; then
	git -C void-packages reset --hard >/dev/null
	void-packages/xbps-src clean
else
	git clone https://github.com/void-linux/void-packages.git
	ln -s void-packages/hostdir/binpkgs binpkgs
fi

git -C void-packages reset --hard >/dev/null
for package in "$@"; do
    [ -e "void-packages/srcpkgs/$package" ] && rm -r "void-packages/srcpkgs/$package"
    cp -r "srcpkgs/$package" void-packages/srcpkgs/
    void-packages/xbps-src pkg "$package"
done
