#!/bin/sh
set -eu
cd "$(dirname "$0")"

if [ ! -d void-packages ]; then
	git clone https://github.com/void-linux/void-packages.git
	ln -s void-packages/hostdir/binpkgs binpkgs
fi

git -C void-packages reset --hard > /dev/null
cp -r srcpkgs/* void-packages/srcpkgs/

if [ $# -gt 0 ]; then
    for package in "$@"; do
        if [ -d "srcpkgs/$package" ]; then
            void-packages/xbps-src pkg "$package"
        else
            echo "Missing package: $package"
        fi
    done
else
	cd srcpkgs
    for package in *; do
        ../void-packages/xbps-src pkg "$package"
    done
fi
