#!/bin/sh
set -eu
cd "$(dirname "$0")"

if [ -e void-packages ]; then
    cd void-packages
    ./xbps-src zap
    git worktree remove --force .
    cd ..
fi

if [ -e binpkgs ]; then
    rm binpkgs
fi
